"""Non-live, incident-neutral helpers for bounded KCD2 native-probe evidence."""

from .correlation import (
    CorrelationDiagnostic,
    CorrelationResult,
    NativeStageCorrelationReport,
    validate_caller_return_lock,
    validate_caller_return_constraint,
    validate_correlation_contract,
    validate_native_stage_correlation,
    validate_owner_constraint,
    validate_owner_function,
)
from .environment import (
    EnvironmentCollectionSpec,
    IndexInstanceSpec,
    ProviderSpec,
    collect_environment_fingerprint,
    compare_environment_fingerprints,
)
from .experiment_controller import (
    ApprovalBinding,
    ExperimentGateError,
    ExperimentMode,
    IdentityDriftError,
    NativeExperimentController,
    NativeExperimentReceipt,
    NativeExperimentStage,
    verify_native_experiment_chain,
    verify_native_experiment_receipt,
)
from .guarded_kcse import (
    GuardedProjectError,
    RawPEImageMapper,
    entry_lock_preflight,
    generate_guarded_project,
    inspect_pe_exports,
    stage_install_and_rollback,
    validate_double_build,
)
from .input_marker_capability import (
    MAX_CANDIDATE_ROUTES,
    evaluate_input_marker_capability,
)
from .legacy_audit import (
    audit_legacy_probe,
    validate_legacy_probe_audit,
    validate_legacy_probe_migration_plan,
)
from .legacy_kcse import summarize, to_markdown
from .limits import (
    HARD_CEILINGS,
    ProbeLimitTracker,
    ProbeLimits,
    evaluate_probe_bundle_limits,
    redact_probe_output,
)
from .overhead import audit_probe_overhead
from .probe_bundle import (
    LegacyV1MigrationContext,
    PROBE_STAGES,
    ProbeBundleValidation,
    migrate_v1_bundle,
    validate_probe_bundle,
    validate_probe_stage_transition,
)
from .playtest_readiness import FAILURE_REASON_CATALOG, probe_playtest_readiness
from .record_layout import (
    MAX_READABLE_SPAN_BYTES,
    LayoutDiagnostic,
    RecordLayoutLintReport,
    discover_readable_span,
    record_layout_lint,
)
from .result_validity import negative_capture_audit, validate_probe_result
from .source_contract import (
    GeneratedProbeContract,
    ProbeSourceContractError,
    ProbeSourceManifestReport,
    generate_probe_contract,
    probe_source_manifest_check,
)
from .runtime_jsonl import (
    RuntimeJsonlLimits,
    RuntimeJsonlWriter,
    RuntimeSessionManifest,
    convert_legacy_kcse,
    summarize_runtime_jsonl,
)
from .runtime_identity import (
    build_runtime_identity_record,
    validate_deployment_binding,
    verify_capture_identity,
)
from .runtime_session_inspection import (
    ExactRuntimeSessionProvider,
    InMemoryRuntimeSessionProvider,
    RuntimeSessionInspector,
    bind_runtime_session_record,
    validate_runtime_session_binding,
)
from .x64dbg_session import (
    CapturedCheckpoint,
    CheckpointCaptureRequest,
    CloseDebugSessionRequest,
    DebuggerHandoffError,
    DebuggerIdentity,
    DebuggerSnapshot,
    GameplayHandoffRequest,
    capture_checkpoint,
    close_debug_session,
    gameplay_handoff_approval_targets,
    prepare_gameplay_handoff,
    session_operation_approval_targets,
)

__all__ = [
    "RuntimeJsonlLimits",
    "RuntimeJsonlWriter",
    "RuntimeSessionManifest",
    "EnvironmentCollectionSpec",
    "ApprovalBinding",
    "audit_probe_overhead",
    "audit_legacy_probe",
    "ExperimentGateError",
    "ExperimentMode",
    "IdentityDriftError",
    "NativeExperimentController",
    "NativeExperimentReceipt",
    "NativeExperimentStage",
    "verify_native_experiment_chain",
    "verify_native_experiment_receipt",
    "GuardedProjectError",
    "RawPEImageMapper",
    "HARD_CEILINGS",
    "LegacyV1MigrationContext",
    "MAX_CANDIDATE_ROUTES",
    "LayoutDiagnostic",
    "MAX_READABLE_SPAN_BYTES",
    "IndexInstanceSpec",
    "ProbeLimitTracker",
    "ProbeLimits",
    "ProviderSpec",
    "PROBE_STAGES",
    "ProbeBundleValidation",
    "ProbeSourceContractError",
    "ProbeSourceManifestReport",
    "RecordLayoutLintReport",
    "GeneratedProbeContract",
    "FAILURE_REASON_CATALOG",
    "CorrelationDiagnostic",
    "CorrelationResult",
    "NativeStageCorrelationReport",
    "convert_legacy_kcse",
    "collect_environment_fingerprint",
    "compare_environment_fingerprints",
    "discover_readable_span",
    "evaluate_probe_bundle_limits",
    "entry_lock_preflight",
    "evaluate_input_marker_capability",
    "generate_guarded_project",
    "generate_probe_contract",
    "inspect_pe_exports",
    "migrate_v1_bundle",
    "negative_capture_audit",
    "redact_probe_output",
    "record_layout_lint",
    "probe_source_manifest_check",
    "probe_playtest_readiness",
    "summarize",
    "summarize_runtime_jsonl",
    "stage_install_and_rollback",
    "to_markdown",
    "validate_probe_bundle",
    "validate_legacy_probe_audit",
    "validate_legacy_probe_migration_plan",
    "validate_probe_result",
    "validate_probe_stage_transition",
    "validate_caller_return_lock",
    "validate_caller_return_constraint",
    "validate_correlation_contract",
    "validate_native_stage_correlation",
    "validate_owner_constraint",
    "validate_owner_function",
    "validate_double_build",
    "build_runtime_identity_record",
    "validate_deployment_binding",
    "verify_capture_identity",
    "ExactRuntimeSessionProvider",
    "InMemoryRuntimeSessionProvider",
    "RuntimeSessionInspector",
    "bind_runtime_session_record",
    "validate_runtime_session_binding",
    "DebuggerHandoffError",
    "DebuggerIdentity",
    "DebuggerSnapshot",
    "GameplayHandoffRequest",
    "CapturedCheckpoint",
    "CheckpointCaptureRequest",
    "CloseDebugSessionRequest",
    "capture_checkpoint",
    "close_debug_session",
    "gameplay_handoff_approval_targets",
    "prepare_gameplay_handoff",
    "session_operation_approval_targets",
]
