"""Deterministic, engine-neutral primitives shared by KCD2 tools."""

from .atomic import atomic_write_bytes, atomic_write_json, atomic_write_text
from .asset_runtime import AssetRuntimeAdapterError, adapt_visual_lighting_runtime
from .audio_haptic_routes import (
    AudioHapticRouteError,
    AudioHapticRouteGraph,
    resolve_audio_haptic_routes_mapping,
)
from .audio_haptic_runtime import AudioHapticRuntimeError, adapt_audio_haptic_runtime
from .capability_preflight import (
    CapabilityPreflightInputs,
    PyGhidraObservation,
    detect_capabilities,
)
from .configuration_audit import (
    CONFIGURATION_PATH_SEMANTICS,
    ConfigurationAudit,
    ConfigurationAuditError,
    ConfigurationPathRule,
    ConfigurationResolution,
    ConfigurationSource,
    audit_configuration,
    audit_configuration_mapping,
    classify_configuration_path,
    resolve_effective_configuration,
    resolve_effective_configuration_mapping,
)
from .containers import (
    ContainerValidation,
    ContainerValidationLimits,
    LegacyPeValidMigration,
    PeValidation,
    adapt_legacy_pe_valid,
    classify_container,
    migrate_legacy_pe_valid,
)
from .cross_tool_identity import (
    CrossToolIdentity,
    IdentityMismatchError,
    assert_same_identity,
    bind_cross_tool_identity,
)
from .diagnostics import Diagnostic, DiagnosticAggregate, aggregate_diagnostics
from .ephemeral_workspace import (
    EphemeralAnalysisWorkspace,
    WorkspaceCleanupError,
    WorkspacePolicyError,
)
from .errors import ERROR_CODE_CATEGORIES, ErrorCategory, ToolError
from .hashing import canonical_json_bytes, sha256_bytes, sha256_file, sha256_json
from .ghidra_export_contract import (
    GhidraExportContractError,
    GhidraHeadlessExportError,
    GhidraHeadlessExportRequest,
    GhidraHeadlessExportResult,
    run_ghidra_headless_export,
    validate_ghidra_export,
)
from .identities import EvidenceIdentity, EvidenceKind, NativeLocation
from .index_contract import classify_contract_state, validate_concrete_input_schema
from .jsonl import BoundedJsonlLimits, BoundedJsonlResult, read_bounded_jsonl
from .localization_release import (
    LocalizationReleaseAcceptanceError,
    LocalizationReleaseReceipt,
    evaluate_localization_release_acceptance,
)
from .paths import canonical_path_key, canonical_relative_path
from .plugin_surface import PublicTool, ToolSurfaceContractError, smoke_test_public_surface
from .portfolio_registry import (
    PortfolioIdentityMismatchError,
    PortfolioRegistry,
    canonicalize_portfolio_registry,
    migrate_portfolio_registry_draft,
)
from .composite_declarations import (
    CompositeDeclaration,
    CompositeDeclarationError,
    CompositeLintResult,
    canonicalize_composite_declaration,
    lint_composite_declaration,
)
from .compatibility_stacks import (
    CompatibilityStackError,
    CompatibilityStackIdentityMismatchError,
    CompatibilityStackManifest,
    canonicalize_compatibility_stack,
    evaluate_compatibility_stack,
    migrate_legacy_compatibility_stack,
)
from .balance_table_rpg_acceptance import (
    BalanceTableRpgAcceptanceError,
    BalanceTableRpgAcceptanceReceipt,
    evaluate_balance_table_rpg_acceptance,
)
from .portfolio_relationships import (
    PortfolioRelationshipCycleError,
    PortfolioRelationshipError,
    PortfolioRelationshipIdentityMismatchError,
    PortfolioRelationshipRegistry,
    canonicalize_portfolio_relationship_registry,
    migrate_legacy_portfolio_relationships,
    validate_portfolio_relationship_dag,
)
from .portfolio_active_state import (
    ActiveSnapshotBinding,
    LatestBootBinding,
    ModOrderBinding,
    PortfolioActiveState,
    PortfolioActiveStateError,
    ProjectInstalledStateBinding,
    RuntimeProjectBinding,
    link_portfolio_active_state,
)
from .project_inventory import (
    ProjectInventory,
    ProjectInventoryError,
    ProviderDiscoveryReceipt,
    inventory_projects,
)
from .results import (
    ContinuationHandle,
    Pagination,
    ResponseLimitError,
    ResponseLimits,
    ResultEnvelope,
    build_bounded_envelope,
    decode_continuation_handle,
)
from .variant_selection import (
    VariantIdentityMismatchError,
    VariantSelectionError,
    VariantSelectionReceipt,
    validate_variant_selection,
)
from .variant_comparison import (
    VariantBoundaryReport,
    VariantComparisonError,
    VariantComparisonReport,
    compare_variants,
    evaluate_variant_release_gate,
    evaluate_variant_rollback_gate,
)
from .variant_topology import (
    VariantTopologyError,
    VariantTopologyReport,
    detect_simultaneously_deployable_variants,
)
__all__ = [
    "BoundedJsonlLimits",
    "BoundedJsonlResult",
    "CapabilityPreflightInputs",
    "AudioHapticRouteError",
    "AudioHapticRouteGraph",
    "AudioHapticRuntimeError",
    "AssetRuntimeAdapterError",
    "ContainerValidation",
    "ContainerValidationLimits",
    "CompositeDeclaration",
    "CompositeDeclarationError",
    "CompositeLintResult",
    "ContinuationHandle",
    "CrossToolIdentity",
    "Diagnostic",
    "DiagnosticAggregate",
    "ERROR_CODE_CATEGORIES",
    "ErrorCategory",
    "EvidenceIdentity",
    "EvidenceKind",
    "GhidraExportContractError",
    "GhidraHeadlessExportError",
    "GhidraHeadlessExportRequest",
    "GhidraHeadlessExportResult",
    "EphemeralAnalysisWorkspace",
    "IdentityMismatchError",
    "LegacyPeValidMigration",
    "LocalizationReleaseAcceptanceError",
    "LocalizationReleaseReceipt",
    "NativeLocation",
    "PeValidation",
    "PublicTool",
    "PortfolioIdentityMismatchError",
    "PortfolioRegistry",
    "PortfolioRelationshipCycleError",
    "PortfolioRelationshipError",
    "PortfolioRelationshipIdentityMismatchError",
    "PortfolioRelationshipRegistry",
    "PortfolioActiveState",
    "PortfolioActiveStateError",
    "ActiveSnapshotBinding",
    "LatestBootBinding",
    "ModOrderBinding",
    "ProjectInstalledStateBinding",
    "RuntimeProjectBinding",
    "ProjectInventory",
    "ProjectInventoryError",
    "ProviderDiscoveryReceipt",
    "PyGhidraObservation",
    "Pagination",
    "ResponseLimitError",
    "ResponseLimits",
    "ResultEnvelope",
    "ToolError",
    "ToolSurfaceContractError",
    "VariantIdentityMismatchError",
    "VariantSelectionError",
    "VariantSelectionReceipt",
    "VariantTopologyError",
    "VariantTopologyReport",
    "WorkspaceCleanupError",
    "WorkspacePolicyError",
    "CONFIGURATION_PATH_SEMANTICS",
    "ConfigurationAudit",
    "ConfigurationAuditError",
    "ConfigurationPathRule",
    "ConfigurationResolution",
    "ConfigurationSource",
    "aggregate_diagnostics",
    "adapt_legacy_pe_valid",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "assert_same_identity",
    "bind_cross_tool_identity",
    "build_bounded_envelope",
    "canonical_json_bytes",
    "canonical_path_key",
    "canonical_relative_path",
    "canonicalize_portfolio_registry",
    "canonicalize_composite_declaration",
    "canonicalize_portfolio_relationship_registry",
    "classify_container",
    "classify_contract_state",
    "detect_capabilities",
    "decode_continuation_handle",
    "migrate_legacy_pe_valid",
    "migrate_portfolio_registry_draft",
    "migrate_legacy_portfolio_relationships",
    "inventory_projects",
    "link_portfolio_active_state",
    "lint_composite_declaration",
    "read_bounded_jsonl",
    "resolve_audio_haptic_routes_mapping",
    "adapt_audio_haptic_runtime",
    "adapt_visual_lighting_runtime",
    "run_ghidra_headless_export",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "smoke_test_public_surface",
    "validate_concrete_input_schema",
    "validate_ghidra_export",
    "validate_variant_selection",
    "VariantBoundaryReport",
    "VariantComparisonError",
    "VariantComparisonReport",
    "compare_variants",
    "evaluate_variant_release_gate",
    "evaluate_variant_rollback_gate",
    "evaluate_localization_release_acceptance",
    "detect_simultaneously_deployable_variants",
    "validate_portfolio_relationship_dag",
    "audit_configuration",
    "audit_configuration_mapping",
    "classify_configuration_path",
    "resolve_effective_configuration",
    "resolve_effective_configuration_mapping",
]
from .approvals import (
    ApprovalError,
    ApprovalLedger,
    ApprovalTarget,
    ApprovalVerifier,
    DirectProcessStateProbe,
    ProcessStateSnapshot,
    approval_binding_sha256,
)
from .crash_triage import CrashTriageError, CrashTriageReport, triage_crash
from .log_diagnosis import (
    AttributionEvidence,
    LogDiagnosis,
    LogDiagnosisError,
    LogDiagnosisProfile,
    LogEventPattern,
    diagnose_latest_boot,
)
from .environment_profiles import (
    ComponentProfile,
    EnvironmentProfile,
    EnvironmentProfileError,
    WorkflowProfile,
    evaluate_environment_profile,
    load_environment_profile,
)

__all__ = [
    "ApprovalError",
    "ApprovalLedger",
    "ApprovalTarget",
    "ApprovalVerifier",
    "DirectProcessStateProbe",
    "ProcessStateSnapshot",
    "approval_binding_sha256",
    "AttributionEvidence",
    "LogDiagnosis",
    "LogDiagnosisError",
    "LogDiagnosisProfile",
    "LogEventPattern",
    "diagnose_latest_boot",
    "CrashTriageError",
    "CrashTriageReport",
    "triage_crash",
    "ComponentProfile",
    "EnvironmentProfile",
    "EnvironmentProfileError",
    "WorkflowProfile",
    "evaluate_environment_profile",
    "load_environment_profile",
    "CompatibilityStackError",
    "CompatibilityStackIdentityMismatchError",
    "CompatibilityStackManifest",
    "BalanceTableRpgAcceptanceError",
    "BalanceTableRpgAcceptanceReceipt",
    "canonicalize_compatibility_stack",
    "evaluate_compatibility_stack",
    "evaluate_balance_table_rpg_acceptance",
    "migrate_legacy_compatibility_stack",
]
